name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  BUILD_TARGET: all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}
    
    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: buspirate 5 firmware
        path: ${{github.workspace}}/build/*.uf2
        retention-days: 7
